----------------------------------------------------------------------------------------------------
-- Finder application config
--
local Ki = spoon.Ki
local Application = Ki.Application
local FocusAndChooseMenuItem = Application.FocusAndChooseMenuItem
local FocusAndSelectMenuItem = Application.FocusAndSelectMenuItem
local FocusAndToggleMenuItem = Application.FocusAndToggleMenuItem
local unmapped = Application.unmapped

return Application {
    name = "Finder",
    shortcuts = {
        Finder = {
            { nil, ",", FocusAndSelectMenuItem { "Finder", "Preferences…" } },
            { nil, "h", FocusAndSelectMenuItem { "Finder", "Hide Finder" } },
            { { "alt" }, "h", FocusAndSelectMenuItem { "Finder", "Hide Others" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Finder", "About Finder" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Finder", "Empty Trash" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Finder", "Empty Trash…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Finder", "Services" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Finder", "Show All" } },
        },
        File = {
            { nil, "d", FocusAndSelectMenuItem { "File", "Duplicate" } },
            { nil, "e", FocusAndSelectMenuItem { "File", "Eject" } },
            { nil, "f", FocusAndSelectMenuItem { "File", "Find" } },
            { nil, "i", FocusAndSelectMenuItem { "File", "Get Info" } },
            { nil, "n", FocusAndSelectMenuItem { "File", "New Finder Window" } },
            { nil, "o", FocusAndSelectMenuItem { "File", "Open" } },
            { nil, "p", FocusAndSelectMenuItem { "File", "Print" } },
            { nil, "t", FocusAndSelectMenuItem { "File", "New Tab" } },
            { nil, "w", FocusAndSelectMenuItem { "File", "Close Window" } },
            { nil, "y", FocusAndSelectMenuItem "Quick Look “.*”" },
            { { "alt" }, "e", FocusAndSelectMenuItem { "File", "Eject" } },
            { { "alt" }, "f", FocusAndSelectMenuItem { "File", "Set Focus To Search Field" } },
            { { "alt" }, "i", FocusAndSelectMenuItem { "File", "Show Inspector" } },
            { { "alt" }, "o", FocusAndSelectMenuItem { "File", "Open and Close Window" } },
            { { "alt" }, "w", FocusAndSelectMenuItem { "File", "Close All" } },
            { { "alt" }, "y", FocusAndSelectMenuItem "Slideshow “.*”" },
            { { "alt", "ctrl" }, "a", FocusAndSelectMenuItem { "File", "Show Original" } },
            { { "ctrl" }, "a", FocusAndSelectMenuItem { "File", "Make Alias" } },
            { { "ctrl" }, "e", FocusAndSelectMenuItem { "File", "Eject" } },
            { { "ctrl" }, "i", FocusAndSelectMenuItem { "File", "Get Summary Info" } },
            { { "ctrl" }, "n", FocusAndSelectMenuItem "New Folder with “.*”" },
            { { "ctrl" }, "o", FocusAndSelectMenuItem { "File", "Open in New Tab" } },
            { { "ctrl" }, "t", FocusAndSelectMenuItem { "File", "Add to Sidebar" } },
            { { "shift" }, "n", FocusAndSelectMenuItem { "File", "New Folder" } },
            { { "shift", "alt" }, "d", FocusAndSelectMenuItem { "File", "Duplicate Exactly" } },
            { { "shift", "ctrl" }, "f", FocusAndSelectMenuItem { "File", "Find by Name…" } },
            { { "shift", "ctrl" }, "t", FocusAndSelectMenuItem { "File", "Add to Dock" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Always Open With" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Compress" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Compress" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Delete Immediately…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Move to Trash" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "New Smart Folder" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Open With" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Rename" } },
        },
        Edit = {
            { nil, "a", FocusAndSelectMenuItem { "Edit", "Select All" } },
            { nil, "c", FocusAndSelectMenuItem { "Edit", "Copy" } },
            { nil, "v", FocusAndSelectMenuItem { "Edit", "Paste" } },
            { nil, "x", FocusAndSelectMenuItem { "Edit", "Cut" } },
            { nil, "z", FocusAndSelectMenuItem { "Edit", "Undo" } },
            { { "alt" }, "a", FocusAndSelectMenuItem { "Edit", "Deselect All" } },
            { { "alt" }, "c", FocusAndSelectMenuItem "Copy “.*” as Pathname" },
            { { "alt" }, "v", FocusAndSelectMenuItem { "Edit", "Move Item Here" } },
            { { "alt", "ctrl" }, "c", FocusAndSelectMenuItem { "Edit", "Copy as Link" } },
            { { "shift" }, "z", FocusAndSelectMenuItem { "Edit", "Redo" } },
            { { "shift", "alt" }, "v", FocusAndSelectMenuItem { "Edit", "Paste Exactly" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Emoji & Symbols" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Show Clipboard" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Start Dictation" } },
        },
        View = {
            { nil, "/", FocusAndSelectMenuItem { "View", "Show Status Bar" } },
            { nil, "1", FocusAndSelectMenuItem { "View", "as Icons" } },
            { nil, "2", FocusAndSelectMenuItem { "View", "as List" } },
            { nil, "3", FocusAndSelectMenuItem { "View", "as Columns" } },
            { nil, "4", FocusAndSelectMenuItem { "View", "as Gallery" } },
            { nil, "j", FocusAndSelectMenuItem { "View", "Show View Options" } },
            { { "alt" }, "p", FocusAndSelectMenuItem { "View", "Show Path Bar" } },
            { { "alt" }, "s", FocusAndSelectMenuItem { "View", "Show Sidebar" } },
            { { "alt" }, "t", FocusAndSelectMenuItem { "View", "Hide Toolbar" } },
            { { "ctrl" }, "0", FocusAndSelectMenuItem { "View", "Use Groups" } },
            { { "ctrl" }, "f", FocusAndToggleMenuItem { "Enter Full Screen", "Exit Full Screen" } },
            { { "shift" }, "\\", FocusAndSelectMenuItem { "View", "Show All Tabs" } },
            { { "shift" }, "p", FocusAndSelectMenuItem { "View", "Show Preview" } },
            { { "shift" }, "t", FocusAndSelectMenuItem { "View", "Show Tab Bar" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Clean Up By" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Clean Up Selection" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Clean Up" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Customize Toolbar…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show Preview Options" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Sort By" } },
        },
        Go = {
            { nil, "[", FocusAndSelectMenuItem { "Go", "Back" } },
            { nil, "]", FocusAndSelectMenuItem { "Go", "Forward" } },
            { nil, "k", FocusAndSelectMenuItem { "Go", "Connect to Server…" } },
            { { "alt" }, "l", FocusAndSelectMenuItem { "Go", "Downloads" } },
            { { "shift" }, "a", FocusAndSelectMenuItem { "Go", "Applications" } },
            { { "shift" }, "c", FocusAndSelectMenuItem { "Go", "Computer" } },
            { { "shift" }, "d", FocusAndSelectMenuItem { "Go", "Desktop" } },
            { { "shift" }, "f", FocusAndSelectMenuItem { "Go", "Recents" } },
            { { "shift" }, "g", FocusAndSelectMenuItem { "Go", "Go to Folder…" } },
            { { "shift" }, "h", FocusAndSelectMenuItem { "Go", "Home" } },
            { { "shift" }, "i", FocusAndSelectMenuItem { "Go", "iCloud Drive" } },
            { { "shift" }, "k", FocusAndSelectMenuItem { "Go", "Network" } },
            { { "shift" }, "l", FocusAndSelectMenuItem { "Go", "Library" } },
            { { "shift" }, "o", FocusAndSelectMenuItem { "Go", "Documents" } },
            { { "shift" }, "r", FocusAndSelectMenuItem { "Go", "AirDrop" } },
            { { "shift" }, "u", FocusAndSelectMenuItem { "Go", "Utilities" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Go", "Enclosing Folder in New Window" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Go", "Enclosing Folder" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Go", "Enclosing Folder" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Go", "Recent Folders" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Go", "Select Startup Disk on Desktop" } },
        },
        Window = {
            { nil, "`", FocusAndSelectMenuItem { "Window", "Cycle Through Windows" } },
            { nil, "m", FocusAndSelectMenuItem { "Window", "Minimize" } },
            { { "alt" }, "m", FocusAndSelectMenuItem { "Window", "Minimize All" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Arrange in Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Bring All to Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Downloads" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Merge All Windows" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Tab to New Window" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Left Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Right Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Show Next Tab" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Show Previous Tab" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Zoom All" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Zoom" } },
        },
        Help = {
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "New to Mac? Tour the Basics" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "See What’s New in macOS" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "macOS Help" } },
        },
    },
}
