----------------------------------------------------------------------------------------------------
-- Mail application config
--
local Ki = spoon.Ki
local Application = Ki.Application
local FocusAndChooseMenuItem = Application.FocusAndChooseMenuItem
local FocusAndSelectMenuItem = Application.FocusAndSelectMenuItem
local FocusAndToggleMenuItem = Application.FocusAndToggleMenuItem
local unmapped = Application.unmapped

return Application {
    name = "Mail",
    shortcuts = {
        Mail = {
            { nil, ",", FocusAndSelectMenuItem { "Mail", "Preferences…" } },
            { nil, "h", FocusAndSelectMenuItem { "Mail", "Hide Mail" } },
            { nil, "q", FocusAndSelectMenuItem { "Mail", "Quit Mail" } },
            { { "alt" }, "h", FocusAndSelectMenuItem { "Mail", "Hide Others" } },
            { { "alt" }, "q", FocusAndSelectMenuItem { "Mail", "Quit and Keep Windows" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mail", "About Mail" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mail", "Accounts…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mail", "Add Account…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Mail", "Services" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mail", "Show All" } },
        },
        File = {
            { nil, "n", FocusAndSelectMenuItem { "File", "New Message" } },
            { nil, "o", FocusAndSelectMenuItem { "File", "Open Messages" } },
            { nil, "p", FocusAndSelectMenuItem { "File", "Print…" } },
            { nil, "s", FocusAndSelectMenuItem { "File", "Save" } },
            { nil, "w", FocusAndSelectMenuItem { "File", "Close" } },
            { nil, "y", FocusAndSelectMenuItem { "File", "Quick Look Attachments…" } },
            { { "alt" }, "n", FocusAndSelectMenuItem { "File", "New Viewer Window" } },
            { { "alt" }, "w", FocusAndSelectMenuItem { "File", "Close All" } },
            { { "shift" }, "a", FocusAndSelectMenuItem { "File", "Attach Files…" } },
            { { "shift" }, "s", FocusAndSelectMenuItem { "File", "Save As…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Export as PDF…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Import Mailboxes…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Import from iPhone" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Save Attachments…" } },
        },
        Edit = {
            { nil, "a", FocusAndSelectMenuItem { "Edit", "Select All" } },
            { nil, "c", FocusAndSelectMenuItem { "Edit", "Copy" } },
            { nil, "k", FocusAndSelectMenuItem { "Edit", "Add Link…" } },
            { nil, "v", FocusAndSelectMenuItem { "Edit", "Paste" } },
            { nil, "x", FocusAndSelectMenuItem { "Edit", "Cut" } },
            { nil, "z", FocusAndSelectMenuItem { "Edit", "Undo" } },
            { { "alt" }, "i", FocusAndSelectMenuItem { "Edit", "Append Selected Messages" } },
            { { "alt" }, "k", FocusAndSelectMenuItem { "Edit", "Remove Link" } },
            { { "shift" }, "v", FocusAndSelectMenuItem { "Edit", "Paste as Quotation" } },
            { { "shift" }, "z", FocusAndSelectMenuItem { "Edit", "Redo" } },
            { { "shift", "alt" }, "v", FocusAndSelectMenuItem { "Edit", "Paste and Match Style" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Attachments" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Complete" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Delete" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Emoji & Symbols" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Find" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Speech" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Spelling and Grammar" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Start Dictation" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Substitutions" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Transformations" } },
        },
        View = {
            { nil, "l", FocusAndToggleMenuItem { "Enable Message Filter", "Disable Message Filter" } },
            { { "alt" }, "b", FocusAndSelectMenuItem { "View", "Bcc Address Field" } },
            { { "alt" }, "r", FocusAndSelectMenuItem { "View", "Reply-To Address Field" } },
            { { "alt" }, "t", FocusAndToggleMenuItem { "Show Toolbar", "Hide Toolbar" } },
            { { "ctrl" }, "f", FocusAndToggleMenuItem { "Enter Full Screen", "Exit Full Screen" } },
            { { "shift" }, "m", FocusAndToggleMenuItem { "Show Mailbox List", "Hide Mailbox List" } },
            { { "shift", "alt" }, "h", FocusAndToggleMenuItem { "Show Favorites Bar", "Hide Favorites Bar" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Cc Address Field" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Collapse All Conversations" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Customize Toolbar…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Expand All Conversations" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Hide Related Messages" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Highlight Conversations" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Message" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Organize by Conversation" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show All Tabs" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show Contact Photo" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show Date and Time" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show Message Size" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show Side Preview" } },
            { unmapped, unmapped, FocusAndToggleMenuItem { "Show Tab Bar", "Hide Tab Bar" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show To/Cc Label" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Sort By" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Use Column Layout" } },
        },
        Mailbox = {
            { { "alt" }, "j", FocusAndSelectMenuItem { "Mailbox", "Erase Junk Mail" } },
            { { "shift" }, "n", FocusAndSelectMenuItem { "Mailbox", "Get New Mail" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Delete Mailbox…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Duplicate Smart Mailbox" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Edit Smart Mailbox…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Mailbox", "Erase Deleted Items" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Export Mailbox…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Mailbox", "Go to Favorite Mailbox" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Mark All Messages as Read" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Mailbox", "Move to Favorite Mailbox" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "New Mailbox…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "New Smart Mailbox Folder…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "New Smart Mailbox…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Rebuild" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Rename Mailbox…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Synchronize “iCloud”" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Take All Accounts Offline" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Mailbox", "Take All Accounts Online" } },
        },
        Message = {
            { nil, "r", FocusAndSelectMenuItem { "Message", "Reply" } },
            { { "alt" }, "l", FocusAndSelectMenuItem { "Message", "Apply Rules" } },
            { { "ctrl" }, "a", FocusAndSelectMenuItem { "Message", "Archive" } },
            { { "ctrl" }, "m", FocusAndSelectMenuItem { "Message", "Move to Predicted Mailbox" } },
            { { "shift" }, "d", FocusAndSelectMenuItem { "Message", "Send Again" } },
            { { "shift" }, "e", FocusAndSelectMenuItem { "Message", "Redirect" } },
            { { "shift" }, "f", FocusAndSelectMenuItem { "Message", "Forward" } },
            { { "shift" }, "j", FocusAndSelectMenuItem { "Message", "Move to Junk" } },
            { { "shift" }, "r", FocusAndSelectMenuItem { "Message", "Reply All" } },
            { { "shift" }, "u", FocusAndSelectMenuItem { "Message", "Mark as Unread" } },
            { { "shift", "ctrl" }, "m", FocusAndSelectMenuItem { "Message", "Unmute" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Message", "Add Sender to Contacts" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Message", "Copy to" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Message", "Flag" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Message", "Forward Message and Parent as Attachments" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Message", "Forward as Attachment" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Message", "Move Again" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Message", "Move to" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Message", "Remove Attachments" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Message", "Set Priority" } },
        },
        Format = {
            { nil, "t", FocusAndSelectMenuItem { "Format", "Show Fonts" } },
            { { "shift" }, "c", FocusAndSelectMenuItem { "Format", "Show Colors" } },
            { { "shift" }, "t", FocusAndSelectMenuItem { "Format", "Make Rich Text" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Format", "Alignment" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Format", "Indentation" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Format", "Lists" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Format", "Quote Level" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Format", "Style" } },
        },
        Window = {
            { nil, "0", FocusAndSelectMenuItem { "Window", "Message Viewer" } },
            { nil, "m", FocusAndSelectMenuItem { "Window", "Minimize" } },
            { { "alt" }, "0", FocusAndSelectMenuItem { "Window", "Activity" } },
            { { "alt" }, "m", FocusAndSelectMenuItem { "Window", "Minimize All" } },
            { { "alt", "ctrl" }, "z", FocusAndSelectMenuItem { "Window", "Zoom All" } },
            { { "ctrl" }, "z", FocusAndSelectMenuItem { "Window", "Zoom" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Arrange in Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Bring All to Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Connection Doctor" } },
            { unmapped, unmapped, FocusAndSelectMenuItem "Inbox (.*)" },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Merge All Windows" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Tab to New Window" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Left Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Right Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Photo Browser" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Previous Recipients" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Show Next Tab" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Show Previous Tab" } },
        },
        Help = {
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "Mail Help" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "What’s New in Mail?" } },
        },
    },
}
