----------------------------------------------------------------------------------------------------
-- Photos application config
--
local Ki = spoon.Ki
local Application = Ki.Application
local FocusAndChooseMenuItem = Application.FocusAndChooseMenuItem
local FocusAndSelectMenuItem = Application.FocusAndSelectMenuItem
local FocusAndToggleMenuItem = Application.FocusAndToggleMenuItem
local unmapped = Application.unmapped

return Application {
    name = "Photos",
    shortcuts = {
        Photos = {
            { nil, ",", FocusAndSelectMenuItem { "Photos", "Preferences…" } },
            { nil, "h", FocusAndSelectMenuItem { "Photos", "Hide Photos" } },
            { nil, "q", FocusAndSelectMenuItem { "Photos", "Quit Photos" } },
            { { "alt" }, "h", FocusAndSelectMenuItem { "Photos", "Hide Others" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Photos", "About Photos" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Photos", "Services" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Photos", "Show All" } },
        },
        File = {
            { nil, "n", FocusAndSelectMenuItem { "File", "New Album" } },
            { nil, "p", FocusAndSelectMenuItem { "File", "Print…" } },
            { nil, "w", FocusAndSelectMenuItem { "File", "Close" } },
            { { "alt" }, "n", FocusAndSelectMenuItem { "File", "New Smart Album…" } },
            { { "shift" }, "i", FocusAndSelectMenuItem { "File", "Import…" } },
            { { "shift" }, "n", FocusAndSelectMenuItem { "File", "New Folder" } },
            { { "shift", "alt" }, "i", FocusAndSelectMenuItem { "File", "Import without Review…" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Consolidate…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Create" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Edit Smart Album…" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Export" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Play Slideshow" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "File", "Share" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Show Referenced File in Finder" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "File", "Show in All Photos" } },
        },
        Edit = {
            { nil, "a", FocusAndSelectMenuItem { "Edit", "Select All" } },
            { nil, "c", FocusAndSelectMenuItem { "Edit", "Copy" } },
            { nil, "f", FocusAndSelectMenuItem { "Edit", "Find" } },
            { nil, "v", FocusAndSelectMenuItem { "Edit", "Paste" } },
            { nil, "x", FocusAndSelectMenuItem { "Edit", "Cut" } },
            { nil, "z", FocusAndSelectMenuItem { "Edit", "Undo Create Album" } },
            { { "shift" }, "a", FocusAndSelectMenuItem { "Edit", "Deselect All" } },
            { { "shift" }, "z", FocusAndSelectMenuItem { "Edit", "Redo" } },
            { { "shift", "alt" }, "v", FocusAndSelectMenuItem { "Edit", "Paste and Match Style" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Emoji & Symbols" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Font" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Select Moment" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Edit", "Spelling and Grammar" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Edit", "Start Dictation" } },
        },
        Image = {
            { nil, "d", FocusAndSelectMenuItem { "Image", "Duplicate Smart Album" } },
            { nil, "e", FocusAndSelectMenuItem { "Image", "Auto Enhance" } },
            { nil, "l", FocusAndSelectMenuItem { "Image", "Hide/Unhide Photo" } },
            { nil, "r", FocusAndSelectMenuItem { "Image", "Rotate Counterclockwise" } },
            { { "alt" }, "e", FocusAndSelectMenuItem { "Image", "Show/Hide Explore View" } },
            { { "alt" }, "l", FocusAndSelectMenuItem { "Image", "Hide/Unhide Photo" } },
            { { "alt" }, "r", FocusAndSelectMenuItem { "Image", "Rotate Clockwise" } },
            { { "ctrl" }, "a", FocusAndSelectMenuItem { "Image", "Add to Album" } },
            { { "shift" }, "c", FocusAndSelectMenuItem { "Image", "Copy Adjustments" } },
            { { "shift" }, "k", FocusAndSelectMenuItem { "Image", "Make Key Photo" } },
            { { "shift" }, "v", FocusAndSelectMenuItem { "Image", "Paste Adjustments" } },
            { { "shift", "alt" }, "d", FocusAndSelectMenuItem { "Image", "Duplicate Photo From Original" } },
            { {  }, ".", FocusAndSelectMenuItem { "Image", "Add to Favorites" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Add to" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Adjust Date and Time..." } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Delete Photo" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Delete Photo" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Delete Photo" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Image", "Edit With" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Flip Horizontal" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Flip Vertical" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "Image", "Location" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Open Viewer" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Reprocess RAW" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Revert to Original" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Show Edit Tools" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Start/Stop Playback" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Turn On Live Photo" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Image", "Use RAW as Original" } },
        },
        View = {
            { nil, "+", FocusAndSelectMenuItem { "View", "Zoom In" } },
            { nil, "-", FocusAndSelectMenuItem { "View", "Zoom Out" } },
            { { "alt" }, "s", FocusAndSelectMenuItem { "View", "Show Thumbnails" } },
            { { "ctrl" }, "f", FocusAndToggleMenuItem { "Enter Full Screen", "Exit Full Screen" } },
            { {  }, "z", FocusAndSelectMenuItem { "View", "Zoom" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Albums" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Always Show Toolbar and Sidebar in Full Screen" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Library" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Metadata" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Projects" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Shared" } },
            { unmapped, unmapped, FocusAndToggleMenuItem { "Show Face Names", "Hide Face Names" } },
            { unmapped, unmapped, FocusAndToggleMenuItem { "Show Hidden Photo Album", "Hide Hidden Photo Album" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show Histogram" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "View", "Show" } },
            { unmapped, unmapped, FocusAndChooseMenuItem { "View", "Sort" } },
        },
        Window = {
            { nil, "i", FocusAndSelectMenuItem { "Window", "Info" } },
            { nil, "k", FocusAndSelectMenuItem { "Window", "Keyword Manager" } },
            { nil, "m", FocusAndSelectMenuItem { "Window", "Minimize" } },
            { { "alt" }, "m", FocusAndSelectMenuItem { "Window", "Minimize All" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Arrange in Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Bring All to Front" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Left Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Move Window to Right Side of Screen" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Photos" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Project Options" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Zoom All" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Window", "Zoom" } },
        },
        Help = {
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "Keyboard Shortcuts" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "Photos Help" } },
            { unmapped, unmapped, FocusAndSelectMenuItem { "Help", "Service and Support" } },
        },
    },
}
